<?php
/** @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
;


/**
 * Generated by PdoOne Version 1.48 Date generated Tue, 16 Jun 2020 19:59:06 -0400. 
 * EDIT THIS CODE.
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class CupcakeRepo
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''cupcakes'','''','array('cupcakes'=>'CupcakeRepo',)','array()');
 * </pre>
 */
class CupcakeRepo extends CupcakeRepoExt
{
    const ME=__CLASS__; 
}