<?php
/** @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */




/**
 * Generated by PdoOne Version 2.2.1 Date generated Sun, 16 Aug 2020 17:47:05 -0400. 
 * EDIT THIS CODE.
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class CupcakeRepo
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''cupcakes'','''','array('cupcakes'=>'CupcakeRepo',)','''');
 * </pre>
 */
class CupcakeRepo extends AbstractCupcakeRepo
{
    const ME=__CLASS__; 
    
  
    
}